# Generated by Django 5.0.6 on 2024-05-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sluc',
            new_name='slug',
        ),
    ]
