# Generated by Django 5.0.6 on 2024-05-11 18:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='menuitem',
            new_name='menu_item',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='menuitem',
            new_name='menu_item',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('menu_item', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'menu_item')},
        ),
    ]
