# Generated by Django 5.0.6 on 2024-05-14 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_alter_category_options_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='LittleLemonAPI.category'),
        ),
    ]
